### ISSUE TITLE
New template on the contributions folder

### ISSUE THREAD

**Issue by sharpgeek** [IARSystems/iar-risc-v-gd32v-eval#11]
Hi @felipe-iar 

I need help!

I tried to use this template project available in the contributions folder as initial reference for my own project for the RISC-V eval board.
I followed all the instructions you mentioned on the `contributions/README.md` document.

Still, whenever I try to simply build the new project (named react), it immediately fails miserably with a fatal error containing the following message about a missing header named **sht3x.h**:

```
Fatal Error[Pe1696]: cannot open source file "sht3x.h" C:\repos\iar-risc-v-gd32v-eval\contributions\react\main.c 17 
            searched: "C:\repos\iar-risc-v-gd32v-eval\contributions\react\" 
            searched: "C:\repos\iar-risc-v-gd32v-eval\contributions\react/../../firmware/GD32VF103_standard_peripheral\" 
            searched: "C:\repos\iar-risc-v-gd32v-eval\contributions\react/../../firmware/GD32VF103_standard_peripheral/include\" 
            searched: "C:\repos\iar-risc-v-gd32v-eval\contributions\react/../../firmware/RISCV/drivers\" 
            searched: "C:\repos\iar-risc-v-gd32v-eval\contributions\react/../../bsp\" 
            searched: "C:\Program Files\IAR_Systems\EWRISCV\1.30.1\riscv\inc\" 
            searched: "C:\Program Files\IAR_Systems\EWRISCV\1.30.1\riscv\inc\c\" 
            current directory: "C:\repos\iar-risc-v-gd32v-eval\contributions\template" 
Error while running C/C++ Compiler 
```

What could possibly be happening?
Please advise.

Thanks in advance.

**Comment by felipe-iar** [comment]
Thanks for pointing it out @sharpgeek 

It was a missing path to the SHT3x sensor headers on the project.template.ewp project file.

It is marked to be fixed on the next push.

Best regards.
